<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PackageSeeder extends Seeder
{
    public function run(): void
    {
        // price stored as piastres (EGP × 100)
        $packages = [
            [
                'slug' => 'well-woman-check',
                'price' => 220000, 'original_price' => 293300,
                'is_featured' => true, 'sample_type' => 'blood', 'sort_order' => 1,
                'categories' => ['womens-health', 'general-wellness'],
                'en_name' => 'Well Woman Check',
                'en_short' => 'A comprehensive health check for women covering key blood markers.',
                'en_desc'  => '<p>The Well Woman Check covers CBC, liver enzymes, kidney function, blood sugar, thyroid, iron studies, cholesterol panel, and female hormones — everything a woman needs to know about her health in one visit.</p>',
                'ar_name' => 'فحص المرأة الشامل',
                'ar_short' => 'فحص صحي شامل للمرأة يغطي أهم المؤشرات الحيوية.',
                'ar_desc'  => '<p>يشمل فحص المرأة الشامل صورة دم كاملة، وظائف الكبد والكلى، سكر الدم، الغدة الدرقية، مخازن الحديد، دهون الدم، والهرمونات الأنثوية — كل ما تحتاجه المرأة في زيارة واحدة.</p>',
            ],
            [
                'slug' => 'well-woman-check-plus',
                'price' => 350000, 'original_price' => 466600,
                'is_featured' => true, 'sample_type' => 'blood', 'sort_order' => 2,
                'categories' => ['womens-health', 'hormones'],
                'en_name' => 'Well Woman Check Plus',
                'en_short' => 'Advanced women\'s health panel with additional hormone and vitamin markers.',
                'en_desc'  => '<p>Includes everything in Well Woman Check plus vitamin D, vitamin B12, DHEA, prolactin, and anti-Müllerian hormone (ovarian reserve).</p>',
                'ar_name' => 'فحص المرأة الشامل المتقدم',
                'ar_short' => 'فحص متقدم للمرأة يضاف إليه فيتامينات وهرمونات إضافية.',
                'ar_desc'  => '<p>يشمل كل ما في فحص المرأة الشامل مع إضافة فيتامين د، ب12، DHEA، بروليكتين، وهرمون AMH (احتياطي المبيض).</p>',
            ],
            [
                'slug' => 'well-man-check',
                'price' => 220000, 'original_price' => 293300,
                'is_featured' => true, 'sample_type' => 'blood', 'sort_order' => 3,
                'categories' => ['mens-health', 'general-wellness'],
                'en_name' => 'Well Man Check',
                'en_short' => 'A comprehensive health check for men covering all essential blood markers.',
                'en_desc'  => '<p>CBC, liver and kidney function, blood sugar, lipid panel, thyroid, PSA (prostate), testosterone, and uric acid — a full picture of male health.</p>',
                'ar_name' => 'فحص الرجل الشامل',
                'ar_short' => 'فحص صحي شامل للرجل يغطي كل المؤشرات الأساسية.',
                'ar_desc'  => '<p>صورة دم كاملة، وظائف كبد وكلى، سكر الدم، دهون الدم، الغدة الدرقية، PSA (البروستاتا)، تيستوستيرون، وحمض البوليك.</p>',
            ],
            [
                'slug' => 'premarital-check-female',
                'price' => 217000, 'original_price' => 289300,
                'is_featured' => true, 'sample_type' => 'blood', 'sort_order' => 4,
                'categories' => ['premarital', 'womens-health'],
                'en_name' => 'Premarital Check – Female',
                'en_short' => 'Essential pre-marriage screening for women including blood group, infections, and hormones.',
                'en_desc'  => '<p>Includes blood group & Rh factor, CBC, hepatitis B & C, HIV, syphilis (VDRL), rubella IgG, CMV, TSH, and blood sugar.</p>',
                'ar_name' => 'فحص ما قبل الزواج – نساء',
                'ar_short' => 'فحوصات ما قبل الزواج الأساسية للمرأة.',
                'ar_desc'  => '<p>يشمل فصيلة الدم والـ Rh، صورة دم كاملة، التهاب الكبد B وC، HIV، الزهري، الحصبة الألمانية، CMV، TSH، وسكر الدم.</p>',
            ],
            [
                'slug' => 'premarital-check-male',
                'price' => 100000, 'original_price' => 133300,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 5,
                'categories' => ['premarital', 'mens-health'],
                'en_name' => 'Premarital Check – Male',
                'en_short' => 'Essential pre-marriage screening for men.',
                'en_desc'  => '<p>Blood group & Rh factor, CBC, hepatitis B & C, HIV, syphilis (VDRL), blood sugar, and semen analysis.</p>',
                'ar_name' => 'فحص ما قبل الزواج – رجال',
                'ar_short' => 'فحوصات ما قبل الزواج الأساسية للرجل.',
                'ar_desc'  => '<p>فصيلة الدم والـ Rh، صورة دم كاملة، التهاب الكبد B وC، HIV، الزهري، سكر الدم، وتحليل السائل المنوي.</p>',
            ],
            [
                'slug' => 'anemia-check',
                'price' => 45000, 'original_price' => 60000,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 6,
                'categories' => ['general-wellness'],
                'en_name' => 'Anemia Check',
                'en_short' => 'Quick screen for anemia and iron deficiency.',
                'en_desc'  => '<p>CBC, serum iron, ferritin, TIBC, and vitamin B12.</p>',
                'ar_name' => 'فحص الأنيميا',
                'ar_short' => 'فحص سريع للأنيميا ونقص الحديد.',
                'ar_desc'  => '<p>صورة دم كاملة، حديد الدم، فيريتين، TIBC، وفيتامين ب12.</p>',
            ],
            [
                'slug' => 'anemia-check-plus',
                'price' => 155000, 'original_price' => 206600,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 7,
                'categories' => ['general-wellness'],
                'en_name' => 'Anemia Check Plus',
                'en_short' => 'Comprehensive anemia panel with bone marrow and hemolytic markers.',
                'en_desc'  => '<p>Includes all Anemia Check markers plus reticulocyte count, LDH, haptoglobin, and hemoglobin electrophoresis.</p>',
                'ar_name' => 'فحص الأنيميا المتقدم',
                'ar_short' => 'فحص شامل للأنيميا يشمل مؤشرات إضافية.',
                'ar_desc'  => '<p>كل مؤشرات فحص الأنيميا الأساسي مع إضافة عد الخلايا الشبكية، LDH، هابتوجلوبين، وهيموجلوبين إليكتروفوريسيس.</p>',
            ],
            [
                'slug' => 'thyroid-check',
                'price' => 50000, 'original_price' => 66600,
                'is_featured' => true, 'sample_type' => 'blood', 'sort_order' => 8,
                'categories' => ['thyroid'],
                'en_name' => 'Thyroid Check',
                'en_short' => 'Complete thyroid function panel (TSH, T3, T4, antibodies).',
                'en_desc'  => '<p>TSH, Free T3, Free T4, anti-TPO antibodies, and anti-thyroglobulin.</p>',
                'ar_name' => 'فحص الغدة الدرقية',
                'ar_short' => 'فحص شامل لوظائف الغدة الدرقية.',
                'ar_desc'  => '<p>TSH، T3 الحر، T4 الحر، أجسام مضادة Anti-TPO، وأجسام مضادة Anti-Thyroglobulin.</p>',
            ],
            [
                'slug' => 'cancer-check-female',
                'price' => 165000, 'original_price' => 220000,
                'is_featured' => true, 'sample_type' => 'blood', 'sort_order' => 9,
                'categories' => ['cancer', 'womens-health'],
                'en_name' => 'Cancer Check – Female',
                'en_short' => 'Female cancer tumor markers panel for early detection.',
                'en_desc'  => '<p>CA-125 (ovarian), CA 15-3 (breast), CEA (bowel), CA 19-9 (pancreas/GI), AFP (liver), and CBC.</p>',
                'ar_name' => 'فحص السرطان – نساء',
                'ar_short' => 'فحص علامات الأورام للمرأة للكشف المبكر.',
                'ar_desc'  => '<p>CA-125 (المبيض)، CA 15-3 (الثدي)، CEA (القولون)، CA 19-9 (البنكرياس والجهاز الهضمي)، AFP (الكبد)، وصورة دم كاملة.</p>',
            ],
            [
                'slug' => 'breast-cancer-prevention',
                'price' => 160000, 'original_price' => 213300,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 10,
                'categories' => ['cancer', 'womens-health'],
                'en_name' => 'Breast Cancer Prevention Package',
                'en_short' => 'Comprehensive breast cancer risk assessment and early detection panel.',
                'en_desc'  => '<p>CA 15-3, CEA, CBC, ESR, LDH, and breast-specific hormonal markers.</p>',
                'ar_name' => 'باقة الوقاية من سرطان الثدي',
                'ar_short' => 'فحص شامل لتقييم خطر سرطان الثدي والكشف المبكر.',
                'ar_desc'  => '<p>CA 15-3، CEA، صورة دم كاملة، سرعة الترسيب، LDH، ومؤشرات هرمونية خاصة بالثدي.</p>',
            ],
            [
                'slug' => 'hair-fall-panel',
                'price' => 140000, 'original_price' => 186600,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 11,
                'categories' => ['womens-health', 'nutrition'],
                'en_name' => 'Hair Fall Panel',
                'en_short' => 'Find the root cause of hair loss with this comprehensive panel.',
                'en_desc'  => '<p>CBC, iron, ferritin, TIBC, zinc, vitamin D, vitamin B12, TSH, T3, T4, DHEA-S, and testosterone.</p>',
                'ar_name' => 'فحص تساقط الشعر',
                'ar_short' => 'اكتشف السبب الحقيقي وراء تساقط الشعر.',
                'ar_desc'  => '<p>صورة دم كاملة، حديد، فيريتين، TIBC، زنك، فيتامين د، ب12، TSH، T3، T4، DHEA-S، وتيستوستيرون.</p>',
            ],
            [
                'slug' => 'acne-panel',
                'price' => 100000, 'original_price' => 133300,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 12,
                'categories' => ['womens-health', 'hormones'],
                'en_name' => 'Acne Panel',
                'en_short' => 'Hormonal and nutritional causes of acne in one panel.',
                'en_desc'  => '<p>CBC, blood sugar, insulin, DHEA-S, testosterone (free & total), LH, FSH, prolactin, and zinc.</p>',
                'ar_name' => 'فحص حب الشباب',
                'ar_short' => 'الأسباب الهرمونية والغذائية لحب الشباب في فحص واحد.',
                'ar_desc'  => '<p>صورة دم كاملة، سكر الدم، إنسولين، DHEA-S، تيستوستيرون (كلي وحر)، LH، FSH، بروليكتين، وزنك.</p>',
            ],
            [
                'slug' => 'menopause-check',
                'price' => 120000, 'original_price' => 160000,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 13,
                'categories' => ['womens-health', 'hormones'],
                'en_name' => 'Menopause Check',
                'en_short' => 'Hormonal assessment for women approaching or in menopause.',
                'en_desc'  => '<p>FSH, LH, estradiol, AMH, progesterone, TSH, bone markers (calcium, vitamin D, alkaline phosphatase).</p>',
                'ar_name' => 'فحص سن اليأس',
                'ar_short' => 'تقييم هرموني للمرأة في مرحلة انقطاع الطمث.',
                'ar_desc'  => '<p>FSH، LH، إستراديول، AMH، بروجيسترون، TSH، ومؤشرات العظام (كالسيوم، فيتامين د، فوسفاتاز قلوي).</p>',
            ],
            [
                'slug' => 'antenatal-check',
                'price' => 150000, 'original_price' => 200000,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 14,
                'categories' => ['womens-health'],
                'en_name' => 'Antenatal Check',
                'en_short' => 'Comprehensive pregnancy follow-up panel for mother and baby safety.',
                'en_desc'  => '<p>Blood group & Rh, CBC, blood sugar, hepatitis B & C, HIV, rubella IgG, toxoplasma, CMV, urine analysis, and TSH.</p>',
                'ar_name' => 'فحص الرعاية السابقة للولادة',
                'ar_short' => 'فحص شامل لمتابعة الحمل لسلامة الأم والجنين.',
                'ar_desc'  => '<p>فصيلة دم وRh، صورة دم كاملة، سكر الدم، التهاب كبد B وC، HIV، حصبة ألمانية، توكسوبلازما، CMV، تحليل بول، وTSH.</p>',
            ],
            [
                'slug' => 'diabetes-followup',
                'price' => 60000, 'original_price' => 80000,
                'is_featured' => true, 'sample_type' => 'blood', 'sort_order' => 15,
                'categories' => ['diabetes'],
                'en_name' => 'Diabetes Follow-up Panel',
                'en_short' => 'Essential monitoring tests for diabetes management.',
                'en_desc'  => '<p>HbA1c, fasting blood sugar, kidney function (creatinine, urea), urine microalbumin, CBC, and lipid profile.</p>',
                'ar_name' => 'متابعة مرضى السكري',
                'ar_short' => 'الفحوصات الأساسية لمتابعة مرضى السكري.',
                'ar_desc'  => '<p>HbA1c، سكر الدم الصائم، وظائف الكلى (كرياتينين، يوريا)، ألبومين البول الدقيق، صورة دم، ودهون الدم.</p>',
            ],
            [
                'slug' => 'heart-check',
                'price' => 80000, 'original_price' => 106600,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 16,
                'categories' => ['heart'],
                'en_name' => 'Heart Check',
                'en_short' => 'Cardiovascular risk assessment panel.',
                'en_desc'  => '<p>Lipid profile (total cholesterol, LDL, HDL, triglycerides), hs-CRP, homocysteine, CBC, blood sugar, and HbA1c.</p>',
                'ar_name' => 'فحص صحة القلب',
                'ar_short' => 'تقييم شامل لعوامل خطر أمراض القلب.',
                'ar_desc'  => '<p>دهون الدم (كوليسترول، LDL، HDL، ثلاثيات الجليسريد)، hs-CRP، هوموسيستين، صورة دم، سكر الدم، وHbA1c.</p>',
            ],
            [
                'slug' => 'stomach-check',
                'price' => 50000, 'original_price' => 66600,
                'is_featured' => false, 'sample_type' => 'blood,breath', 'sort_order' => 17,
                'categories' => ['gut-health'],
                'en_name' => 'Stomach Check',
                'en_short' => 'H. pylori detection and basic digestive health markers.',
                'en_desc'  => '<p>H. pylori antibody (IgG & IgM), urea breath test option, liver enzymes, and CBC.</p>',
                'ar_name' => 'فحص المعدة',
                'ar_short' => 'الكشف عن جرثومة المعدة ومؤشرات الصحة الهضمية.',
                'ar_desc'  => '<p>أجسام مضادة H. pylori (IgG وIgM)، اختبار اليوريا بالتنفس، إنزيمات الكبد، وصورة دم كاملة.</p>',
            ],
            [
                'slug' => 'food-allergy-panel-30',
                'price' => 85000, 'original_price' => 113300,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 18,
                'categories' => ['allergy'],
                'en_name' => 'Food Allergy Panel 30',
                'en_short' => 'IgE antibody testing for 30 of the most common food allergens.',
                'en_desc'  => '<p>Tests for IgE antibodies to 30 common foods including milk, eggs, wheat, nuts, fish, and more.</p>',
                'ar_name' => 'فحص حساسية الطعام 30',
                'ar_short' => 'قياس الأجسام المضادة IgE لـ 30 نوعاً من أكثر مسببات الحساسية شيوعاً.',
                'ar_desc'  => '<p>يقيس أجسام IgE المضادة لـ 30 نوعاً من الأطعمة الشائعة كالحليب، البيض، القمح، المكسرات، والأسماك.</p>',
            ],
            [
                'slug' => 'celiac-panel',
                'price' => 160000, 'original_price' => 213300,
                'is_featured' => false, 'sample_type' => 'blood', 'sort_order' => 19,
                'categories' => ['allergy', 'gut-health'],
                'en_name' => 'Celiac Panel',
                'en_short' => 'Complete celiac disease diagnostic panel.',
                'en_desc'  => '<p>Anti-tissue transglutaminase (tTG-IgA & IgG), anti-endomysial antibodies, total IgA, and anti-gliadin antibodies.</p>',
                'ar_name' => 'فحص مرض السيلياك',
                'ar_short' => 'فحص شامل لتشخيص الحساسية لمرض السيلياك.',
                'ar_desc'  => '<p>Anti-tTG (IgA وIgG)، أجسام مضادة للإندوميسيوم، IgA الكلي، وأجسام مضادة للجليادين.</p>',
            ],
            [
                'slug' => 'kids-health-check',
                'price' => 75000, 'original_price' => 100000,
                'is_featured' => true, 'sample_type' => 'blood', 'sort_order' => 20,
                'categories' => ['kids'],
                'en_name' => 'Kids Health Check',
                'en_short' => 'Essential health screening for children covering growth and immunity.',
                'en_desc'  => '<p>CBC, iron studies, ferritin, vitamin D, calcium, blood sugar, and lead levels.</p>',
                'ar_name' => 'فحص صحة الأطفال',
                'ar_short' => 'الفحوصات الأساسية للأطفال لمتابعة النمو والمناعة.',
                'ar_desc'  => '<p>صورة دم كاملة، مخازن الحديد، فيريتين، فيتامين د، كالسيوم، سكر الدم، ومستوى الرصاص.</p>',
            ],
        ];

        foreach ($packages as $pkg) {
            // resolve category IDs
            $categoryIds = DB::table('test_categories')
                ->whereIn('slug', $pkg['categories'])
                ->pluck('id')
                ->toArray();

            $pkgId = DB::table('packages')->insertGetId([
                'slug'           => $pkg['slug'],
                'price'          => $pkg['price'],
                'original_price' => $pkg['original_price'],
                'is_active'      => true,
                'is_featured'    => $pkg['is_featured'],
                'sample_type'    => $pkg['sample_type'],
                'sort_order'     => $pkg['sort_order'],
                'created_at'     => now(),
                'updated_at'     => now(),
            ]);

            DB::table('package_translations')->insert([
                [
                    'package_id'        => $pkgId,
                    'locale'            => 'en',
                    'name'              => $pkg['en_name'],
                    'short_description' => $pkg['en_short'],
                    'description'       => $pkg['en_desc'],
                    'created_at'        => now(),
                    'updated_at'        => now(),
                ],
                [
                    'package_id'        => $pkgId,
                    'locale'            => 'ar',
                    'name'              => $pkg['ar_name'],
                    'short_description' => $pkg['ar_short'],
                    'description'       => $pkg['ar_desc'],
                    'created_at'        => now(),
                    'updated_at'        => now(),
                ],
            ]);

            foreach ($categoryIds as $catId) {
                DB::table('package_category')->insert([
                    'package_id'  => $pkgId,
                    'category_id' => $catId,
                ]);
            }
        }
    }
}
